spring:
  datasource:
    url: jdbc:mysql://120.55.53.207:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zt123456!
logging:
  level:
    root: info #日志配置DEBUG,INFO,WARN,ERROR
    com.macro.mall: debug
    com.macro.mall.demo.service.FeignAdminService: debug