spring:
  datasource:
    url: jdbc:mysql://db:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: Zt123456!
  data:
    mongodb:
      host: mongo
      port: 27017
      database: mall-port
  redis:
    host: redis # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: #不设置密码
  rabbitmq:
    host: rabbit
    port: 5672
    virtual-host: /mall
    username: abc
    password: 123
    publisher-confirms: true #如果对异步消息需要回调必须设置为true

